
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftOR_OPERATORleftAND_OPERATORnonassocCOMPARISON_OPERATORnonassocNOT_OPERATORleftLEFT_PARENTHESESRIGHT_PARENTHESESAND_OPERATOR COMPARISON_OPERATOR FIELD_NAME LEFT_PARENTHESES NOT_OPERATOR NUMBER_LITERAL OR_OPERATOR RIGHT_PARENTHESES START_WHERE STRING_LITERALstart : START_WHERE expression\n             | expressionexpression :   expression OR_OPERATOR expression\n                    | expression AND_OPERATOR expressionexpression :   FIELD_NAME COMPARISON_OPERATOR number_value\n                    | FIELD_NAME COMPARISON_OPERATOR string_valuenumber_value : NUMBER_LITERALstring_value : STRING_LITERALexpression : LEFT_PARENTHESES expression RIGHT_PARENTHESES'
    
_lr_action_items = {'START_WHERE':([0,],[2,]),'FIELD_NAME':([0,2,5,7,8,],[4,4,4,4,4,]),'LEFT_PARENTHESES':([0,2,5,7,8,],[5,5,5,5,5,]),'$end':([1,3,6,11,12,13,14,15,16,17,],[0,-2,-1,-3,-4,-5,-6,-7,-8,-9,]),'OR_OPERATOR':([3,6,10,11,12,13,14,15,16,17,],[7,7,7,-3,-4,-5,-6,-7,-8,-9,]),'AND_OPERATOR':([3,6,10,11,12,13,14,15,16,17,],[8,8,8,8,-4,-5,-6,-7,-8,-9,]),'COMPARISON_OPERATOR':([4,],[9,]),'NUMBER_LITERAL':([9,],[15,]),'STRING_LITERAL':([9,],[16,]),'RIGHT_PARENTHESES':([10,11,12,13,14,15,16,17,],[17,-3,-4,-5,-6,-7,-8,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'expression':([0,2,5,7,8,],[3,6,10,11,12,]),'number_value':([9,],[13,]),'string_value':([9,],[14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> START_WHERE expression','start',2,'p_start_where','parser.py',80),
  ('start -> expression','start',1,'p_start_where','parser.py',81),
  ('expression -> expression OR_OPERATOR expression','expression',3,'p_binary_operators','parser.py',89),
  ('expression -> expression AND_OPERATOR expression','expression',3,'p_binary_operators','parser.py',90),
  ('expression -> FIELD_NAME COMPARISON_OPERATOR number_value','expression',3,'p_expr_field','parser.py',94),
  ('expression -> FIELD_NAME COMPARISON_OPERATOR string_value','expression',3,'p_expr_field','parser.py',95),
  ('number_value -> NUMBER_LITERAL','number_value',1,'p_number_literal','parser.py',99),
  ('string_value -> STRING_LITERAL','string_value',1,'p_string_literal','parser.py',103),
  ('expression -> LEFT_PARENTHESES expression RIGHT_PARENTHESES','expression',3,'p_expression_group','parser.py',107),
]
